### ISSUE TITLE
Allow Admin to set node selectors

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge-driver-k8s#18]
### Description

Currently node selectors are hard coded to `role=management` and `role=projects` this means that any cluster requires at least 2 nodes and they must be suitably labelled.

This should be configurable to allow for single node testing and for other node topologies.

**Comment by knolleary** [comment]
What's the user story this enables?

**Comment by hardillb** [comment]
**As a** K8s System Administrator
**I want to** decide which nodes in my cluster the FlowForge Application and Projects run on
**So that** I can provision the right capacity to meet demand

Currently the helm chart and kubernetes driver assume that there are at least 2 nodes in the cluster. One tagged with `role=managment` and one or more with `role=projects`.

The FlowForge app will run on the node tagged `role=management` and the projects will run on the nodes tagged `role=projects`

This currenty requires a cluster to have at least 2 nodes. For small scale testing this is a problem but it also enforces constraints on the admin that are not required, but are a choice I made early on. Allowing these to be configured allows much greater flexibility.
