### ISSUE TITLE
Question about google home

### ISSUE THREAD

**Issue by azxo1** [flowforge/flowforge-driver-k8s#34]
### Story

Question about google home

### Description

Regards!

I use the google home you wrote in node red. All due respect for that!

My question would be, how can I change integer 23 in the code below with google assistant? Thank you very much!

(I'm sorry I do not speak English. Google translator)

msg.payload = Number(msg.payload)-10;
if (msg.payload < 23) {msg.payload = "on";}
else {
  {msg.payload = "off"}
}
return msg;

**Comment by hardillb** [comment]
This has nothing to do with FlowForge. The Google Home Assistant node's webpage has clear instructions about where to ask questions
