### ISSUE TITLE
Review how we log responses from calls to K8s APIs

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge-driver-k8s#75]
### Description

Review all calls to K8s APIs to ensure we log failures clearly.

While all the calls to create Ingress objects would have shown as succeeding for the AWS ALB limit problem we should still look to see if there are things we can do better.

**Comment by Pezmc** [comment]
Is there a way we can force this to verify?

**Comment by hardillb** [comment]
Only by me asserting it has been done, we can not force failures from the underlying K8s.

Move it to done
